version: "3"

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf

  php:
    build: .
    volumes:
      - ../:/code

  data:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=base_test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
